version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: myapp-server
    container_name: backend_c
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_c
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_c
    volumes:
      - ./frontend/:/usr/app/src
      - /app/src/node_modules
    depends_on:
      - backend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  data:
