version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: myapp-server
    container_name: backend_c
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_PORT=3001
      - DB_URI=mongodb+srv://aljosa:nK4hUAF0hQjLLBwT@reactdatabase.upbxcew.mongodb.net/?retryWrites=true&w=majority&appName=ReactDatabase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_c
    volumes:
      - ./frontend/:/usr/app/src
      - /app/src/node_modules
    depends_on:
      - backend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  data:
