name: Deploy

on:
  push:
    branches:
      - aljosa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ReactFinal/backend

      - name: Install
        run: npm install

      - name: Run Typecheck
        run: npm run typecheck

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend-prod
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aljosaferi/sistemska_administracija:frontend-prod

      - name: Build and push backend-prod
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aljosaferi/sistemska_administracija:backend-prod